on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-node :
    runs-on: ubuntu-latest
    container: node:16
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: cd backend node index.js

