on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-node :
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - run: "18.17.1"
      - run: "9.6.7"
      - uses: actions/checkout@v3
      - run: npm install
      - run: node index.js