on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-node :
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: node index.js
    - name: Start MongoDB
      - uses: supercharge/mongodb-github-action@1.6.0
        with:
        mongodb-version: ${{ matrix.mongodb-version }} 
      - run: npm install
       