name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.4.14', '4.2.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Start MongoDB
      uses: MongoCamp/mongodb-github-action@1.0.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: curl mongodb+srv://ermeet13:pass123@cluster03.xnikdir.mongodb.net/PO
